{% set name = "mkdocs-glightbox" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8fafe8d9c2b824fb023f17fe76339528aa2ae9b722fc81882e648fcbfcd0d1e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - selectolax ==0.3.29

test:
  imports:
    - mkdocs_glightbox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://blueswen.github.io/mkdocs-glightbox
  summary: MkDocs plugin supports image lightbox with GLightbox.
  dev_url: https://github.com/Blueswen/mkdocs-glightbox
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rtlee
