{% set name = "mkdocs-glightbox" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-glightbox-{{ version }}.tar.gz
  sha256: 4e890140a97dd4ad128cb92174384bd0ac33adec3304bbd2b7c48d0847685c4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - mkdocs_glightbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://blueswen.github.io/mkdocs-glightbox
  summary: MkDocs plugin supports image lightbox with GLightbox.
  dev_url: https://github.com/Blueswen/mkdocs-glightbox
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rtlee
