{% set name = "mkdocs-glightbox" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-glightbox-{{ version }}.tar.gz
  sha256: 392b34207bf95991071a16d5f8916d1d2f2cd5d5bb59ae2997485ccd778c70d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - mkdocs_glightbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://blueswen.github.io/mkdocs-glightbox
  summary: MkDocs plugin supports image lightbox with GLightbox.
  dev_url: https://github.com/Blueswen/mkdocs-glightbox
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rtlee
